# Generated by Django 6.1.2 on 2026-10-08 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojuegos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amigo',
            options={'verbose_name': 'Amistad', 'verbose_name_plural': 'Amistades'},
        ),
        migrations.AlterModelOptions(
            name='grupo',
            options={'verbose_name': 'Grupo de videojuegos', 'verbose_name_plural': 'Grupos de videojuegos'},
        ),
        migrations.AlterModelOptions(
            name='videojuego',
            options={'verbose_name': 'Videojuego', 'verbose_name_plural': 'Videojuegos'},
        ),
        migrations.AddField(
            model_name='grupo',
            name='creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grupo',
            name='miembros',
            field=models.ManyToManyField(blank=True, related_name='grupos_pertenecientes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='amigo',
            name='amigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amigos_de', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='amigo',
            unique_together={('usuario', 'amigo')},
        ),
    ]
